### ISSUE TITLE
Using more than one word for answer

### ISSUE THREAD

**Issue by Senagb** [Steven-Hewitt/QA-with-Tensorflow#7]
I am trying to use you code for QA system with answer contains more than one word, but I am not getting anywhere, could you please guide me?

**Comment by afifahapril** [comment]
Hi, have you found the answer for QA system with answer more than one word?

**Comment by Senagb** [comment]
I have used allennlp framework for that, you can find full implementation for different models.

**Comment by afifahapril** [comment]
> I have used allennlp framework for that, you can find full implementation for different models.

so you don't use dynamic memory network?
